name: Compile AVKI

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install GCC Compiler
      run: sudo apt-get update && sudo apt-get install -y gcc

    - name: Compile C Code
      run: gcc -O3 src/main.c -o AVKI

    - name: Generate Tag Name
      id: tag
      run: echo "release_tag=v$(date +'%Y.%m.%d-%H%M%S')" >> $GITHUB_OUTPUT

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        name: "AVKI (${{ steps.tag.outputs.release_tag }})"
        draft: false
        prerelease: false
        files: AVKI
